/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BuiSideDrawer {
        "open": () => Promise<void>;
        "opened": boolean;
        "title": string;
    }
    interface BuiSpinner {
    }
    interface BuiStockFinder {
    }
    interface BuiStockPrice {
        "stockSymbol": string;
    }
    interface BuiTooltip {
        "body": string;
    }
}
export interface BuiStockFinderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBuiStockFinderElement;
}
declare global {
    interface HTMLBuiSideDrawerElement extends Components.BuiSideDrawer, HTMLStencilElement {
    }
    var HTMLBuiSideDrawerElement: {
        prototype: HTMLBuiSideDrawerElement;
        new (): HTMLBuiSideDrawerElement;
    };
    interface HTMLBuiSpinnerElement extends Components.BuiSpinner, HTMLStencilElement {
    }
    var HTMLBuiSpinnerElement: {
        prototype: HTMLBuiSpinnerElement;
        new (): HTMLBuiSpinnerElement;
    };
    interface HTMLBuiStockFinderElement extends Components.BuiStockFinder, HTMLStencilElement {
    }
    var HTMLBuiStockFinderElement: {
        prototype: HTMLBuiStockFinderElement;
        new (): HTMLBuiStockFinderElement;
    };
    interface HTMLBuiStockPriceElement extends Components.BuiStockPrice, HTMLStencilElement {
    }
    var HTMLBuiStockPriceElement: {
        prototype: HTMLBuiStockPriceElement;
        new (): HTMLBuiStockPriceElement;
    };
    interface HTMLBuiTooltipElement extends Components.BuiTooltip, HTMLStencilElement {
    }
    var HTMLBuiTooltipElement: {
        prototype: HTMLBuiTooltipElement;
        new (): HTMLBuiTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "bui-side-drawer": HTMLBuiSideDrawerElement;
        "bui-spinner": HTMLBuiSpinnerElement;
        "bui-stock-finder": HTMLBuiStockFinderElement;
        "bui-stock-price": HTMLBuiStockPriceElement;
        "bui-tooltip": HTMLBuiTooltipElement;
    }
}
declare namespace LocalJSX {
    interface BuiSideDrawer {
        "opened"?: boolean;
        "title"?: string;
    }
    interface BuiSpinner {
    }
    interface BuiStockFinder {
        "onBuiSymbolselected"?: (event: BuiStockFinderCustomEvent<string>) => void;
    }
    interface BuiStockPrice {
        "stockSymbol"?: string;
    }
    interface BuiTooltip {
        "body"?: string;
    }
    interface IntrinsicElements {
        "bui-side-drawer": BuiSideDrawer;
        "bui-spinner": BuiSpinner;
        "bui-stock-finder": BuiStockFinder;
        "bui-stock-price": BuiStockPrice;
        "bui-tooltip": BuiTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bui-side-drawer": LocalJSX.BuiSideDrawer & JSXBase.HTMLAttributes<HTMLBuiSideDrawerElement>;
            "bui-spinner": LocalJSX.BuiSpinner & JSXBase.HTMLAttributes<HTMLBuiSpinnerElement>;
            "bui-stock-finder": LocalJSX.BuiStockFinder & JSXBase.HTMLAttributes<HTMLBuiStockFinderElement>;
            "bui-stock-price": LocalJSX.BuiStockPrice & JSXBase.HTMLAttributes<HTMLBuiStockPriceElement>;
            "bui-tooltip": LocalJSX.BuiTooltip & JSXBase.HTMLAttributes<HTMLBuiTooltipElement>;
        }
    }
}
